export const ActionTypes={
    ADD_PRODUCT:"ADD_PRODUCT",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    DECREMENT_QUANTITY : "DECREMENT_QUANTITY",
    INCREMENT_QUANTITY :"INCREMENT_QUANTITY",
}